kind: secret
name: GCR_USERNAME
get:
  path: kv/data/lab/droneci
  name: GCR_USERNAME
---
kind: secret
name: GCR_PASSWORD
get:
  path: kv/data/lab/droneci
  name: GCR_PASSWORD
---
kind: secret
name: GITEA_SSH_KEY
get:
  path: kv/data/lab/droneci
  name: GITEA_SSH_KEY
---
kind: secret
name: GITEA_KNOWN_HOSTS
get:
  path: kv/data/lab/droneci
  name: GITEA_KNOWN_HOSTS
---
kind: pipeline
type: docker
name: Build and push

trigger:
  branch:
    - main
  event:
    - push

steps:
  - name: Build and push
    image: plugins/docker
    settings:
      username:
        from_secret: GCR_USERNAME
      password:
        from_secret: GCR_PASSWORD
      repo: "git.lab.kvd.studio/${DRONE_REPO}"
      registry: git.lab.kvd.studio
      tags:
        - "${DRONE_COMMIT_SHA}"

  - name: Update manifest repo
    image: git.lab.kvd.studio/r/update-manifest-image-tag:v0.1
    settings:
      ssh_key:
        from_secret: GITEA_SSH_KEY
      known_hosts:
        from_secret: GITEA_KNOWN_HOSTS
      repo_name: apod
      helm_values_path: apod/apod/values.yaml
      yaml_image_tag_path: ".image.tag"
      image_tag: ${DRONE_COMMIT_SHA}
      app_name: apod
